/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir_kelompok2;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alitz
 */
public class GudangProsesView extends javax.swing.JFrame {
    DefaultTableModel model;
    DefaultTableModel model2;
    private int id_user;
    private String username;
    private boolean login = false;

    /**
     * Creates new form GudangProsesView
     */
    public GudangProsesView(String username, boolean login) throws SQLException {
        initComponents();
        stokHabis.setText("3");
        stokHabis.setEditable(false);
        btnCek2.setEnabled(false);
        isiAtributTabel();
        isiAtributTabelSuply();
        this.username = username;
        this.id_user = getId(username);
        try {
            tampilkanProduk ();
        } catch (SQLException ex) {
            Logger.getLogger(GudangProsesView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuManager = new javax.swing.JPanel();
        labelMenu = new javax.swing.JLabel();
        labelMerk = new javax.swing.JLabel();
        monitorManager = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnSuply = new javax.swing.JButton();
        mainGudang = new javax.swing.JPanel();
        monitorBarang = new javax.swing.JPanel();
        judulGudang = new javax.swing.JPanel();
        labelJudulGudang = new javax.swing.JLabel();
        bodyGudang = new javax.swing.JPanel();
        panelTabelGudang = new javax.swing.JScrollPane();
        tabelGudang = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        labelCariBarang = new javax.swing.JLabel();
        inputCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnStok = new javax.swing.JButton();
        tanggalExp = new com.toedter.calendar.JDateChooser();
        cekExp = new javax.swing.JLabel();
        cekBoxHabis = new javax.swing.JCheckBox();
        btnClear = new javax.swing.JButton();
        btnCek = new javax.swing.JButton();
        stokHabis = new javax.swing.JTextField();
        btnCek2 = new javax.swing.JButton();
        tambahBarang = new javax.swing.JPanel();
        headerTambah = new javax.swing.JPanel();
        judulTambah = new javax.swing.JLabel();
        bodyTambahGudang = new javax.swing.JPanel();
        labelNama = new javax.swing.JLabel();
        labelHarga = new javax.swing.JLabel();
        labelStok = new javax.swing.JLabel();
        teksNama = new javax.swing.JTextField();
        teksHarga = new javax.swing.JTextField();
        teksStok = new javax.swing.JTextField();
        tanggalMasukTambah = new com.toedter.calendar.JDateChooser();
        labelTanggalMasuk = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        llabelKadaluarsa = new javax.swing.JLabel();
        tanggalKadaluarsa = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        inputHargaBeli = new javax.swing.JTextField();
        updateBarang = new javax.swing.JPanel();
        headerUbah = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bodyUbah = new javax.swing.JPanel();
        labelUbahNama = new javax.swing.JLabel();
        labelUbahHarga = new javax.swing.JLabel();
        labelUbahStok = new javax.swing.JLabel();
        labelUbahKadaluarsa = new javax.swing.JLabel();
        teksUbahNama = new javax.swing.JTextField();
        teksUbahHarga = new javax.swing.JTextField();
        tanggalUbahKadaluarsa = new com.toedter.calendar.JDateChooser();
        btnSimpan = new javax.swing.JButton();
        btnBatalUbah = new javax.swing.JButton();
        outputStok = new javax.swing.JLabel();
        labelHargaBeli = new javax.swing.JLabel();
        teksHargaBeli = new javax.swing.JTextField();
        tambahStok = new javax.swing.JPanel();
        headerStok = new javax.swing.JPanel();
        judulStok = new javax.swing.JLabel();
        bodyStok = new javax.swing.JPanel();
        labelNamaStok = new javax.swing.JLabel();
        labelHargaStok = new javax.swing.JLabel();
        labelStokSekarang = new javax.swing.JLabel();
        labelMasuk = new javax.swing.JLabel();
        labelTanggalKadaluarsa = new javax.swing.JLabel();
        labelTambahStok = new javax.swing.JLabel();
        teksTambahanStok = new javax.swing.JTextField();
        tanggalMasuk = new com.toedter.calendar.JDateChooser();
        tanggalExpStok = new com.toedter.calendar.JDateChooser();
        namaBarang = new javax.swing.JLabel();
        HargaBarang = new javax.swing.JLabel();
        stokSekarang = new javax.swing.JLabel();
        btnTambahStok = new javax.swing.JButton();
        btnSelesai = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelBeli = new javax.swing.JLabel();
        outputHargaBeli = new javax.swing.JLabel();
        suply = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelSuply = new javax.swing.JTable();
        cari = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuManager.setBackground(new java.awt.Color(0, 0, 153));

        labelMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelMenu.setForeground(new java.awt.Color(255, 255, 255));
        labelMenu.setText("Menu :");

        labelMerk.setBackground(new java.awt.Color(255, 255, 255));
        labelMerk.setFont(new java.awt.Font("Adobe Caslon Pro", 3, 18)); // NOI18N
        labelMerk.setForeground(new java.awt.Color(255, 255, 255));
        labelMerk.setText("<html> \n<p><center>Kasir<br>Sejahtera..</center></p>\n</html>");

        monitorManager.setText("barang");
        monitorManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monitorManagerActionPerformed(evt);
            }
        });

        btnLogout.setText("logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnSuply.setText("Suply");
        btnSuply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuplyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuManagerLayout = new javax.swing.GroupLayout(menuManager);
        menuManager.setLayout(menuManagerLayout);
        menuManagerLayout.setHorizontalGroup(
            menuManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuManagerLayout.createSequentialGroup()
                .addGroup(menuManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuManagerLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(labelMenu)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(menuManagerLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(menuManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMerk, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addGroup(menuManagerLayout.createSequentialGroup()
                                .addGroup(menuManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnLogout)
                                    .addComponent(monitorManager, javax.swing.GroupLayout.PREFERRED_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(btnSuply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        menuManagerLayout.setVerticalGroup(
            menuManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuManagerLayout.createSequentialGroup()
                .addComponent(labelMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(labelMenu)
                .addGap(18, 18, 18)
                .addComponent(monitorManager)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSuply)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(53, 53, 53))
        );

        mainGudang.setLayout(new java.awt.CardLayout());

        labelJudulGudang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelJudulGudang.setText("Halo Gudang, Semangat !!!");

        javax.swing.GroupLayout judulGudangLayout = new javax.swing.GroupLayout(judulGudang);
        judulGudang.setLayout(judulGudangLayout);
        judulGudangLayout.setHorizontalGroup(
            judulGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(judulGudangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelJudulGudang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        judulGudangLayout.setVerticalGroup(
            judulGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, judulGudangLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(labelJudulGudang)
                .addGap(25, 25, 25))
        );

        tabelGudang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        panelTabelGudang.setViewportView(tabelGudang);

        btnEdit.setBackground(new java.awt.Color(0, 0, 255));
        btnEdit.setText("Edit");
        btnEdit.setToolTipText("");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnAdd.setText("tambah barang");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        labelCariBarang.setText("Cari Barang :");

        inputCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCariActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnStok.setText("update stok");
        btnStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStokActionPerformed(evt);
            }
        });

        tanggalExp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tanggalExpMouseClicked(evt);
            }
        });

        cekExp.setText("Cek Exp :");

        cekBoxHabis.setText("Stok < =");
        cekBoxHabis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cekBoxHabisMouseClicked(evt);
            }
        });
        cekBoxHabis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekBoxHabisActionPerformed(evt);
            }
        });

        btnClear.setText("clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnCek.setText("cek");
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });

        stokHabis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokHabisActionPerformed(evt);
            }
        });

        btnCek2.setText("cek");
        btnCek2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCek2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bodyGudangLayout = new javax.swing.GroupLayout(bodyGudang);
        bodyGudang.setLayout(bodyGudangLayout);
        bodyGudangLayout.setHorizontalGroup(
            bodyGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyGudangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelTabelGudang)
                    .addGroup(bodyGudangLayout.createSequentialGroup()
                        .addGroup(bodyGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bodyGudangLayout.createSequentialGroup()
                                .addComponent(cekExp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addComponent(tanggalExp, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(bodyGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bodyGudangLayout.createSequentialGroup()
                                .addGroup(bodyGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cekBoxHabis)
                                    .addGroup(bodyGudangLayout.createSequentialGroup()
                                        .addComponent(labelCariBarang)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inputCari, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(bodyGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bodyGudangLayout.createSequentialGroup()
                                        .addComponent(btnCari)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE))
                                    .addGroup(bodyGudangLayout.createSequentialGroup()
                                        .addGap(0, 8, Short.MAX_VALUE)
                                        .addComponent(stokHabis, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCek2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                        .addGroup(bodyGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnStok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(bodyGudangLayout.createSequentialGroup()
                                .addComponent(btnEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDelete))
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(19, 19, 19))
        );
        bodyGudangLayout.setVerticalGroup(
            bodyGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyGudangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bodyGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cekExp)
                        .addComponent(btnAdd))
                    .addGroup(bodyGudangLayout.createSequentialGroup()
                        .addGroup(bodyGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCek)
                            .addComponent(tanggalExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)))
                .addGroup(bodyGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyGudangLayout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(btnStok))
                    .addGroup(bodyGudangLayout.createSequentialGroup()
                        .addGroup(bodyGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCek2)
                            .addComponent(stokHabis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cekBoxHabis))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bodyGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(labelCariBarang)
                    .addComponent(inputCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTabelGudang, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout monitorBarangLayout = new javax.swing.GroupLayout(monitorBarang);
        monitorBarang.setLayout(monitorBarangLayout);
        monitorBarangLayout.setHorizontalGroup(
            monitorBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judulGudang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bodyGudang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        monitorBarangLayout.setVerticalGroup(
            monitorBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monitorBarangLayout.createSequentialGroup()
                .addComponent(judulGudang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bodyGudang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainGudang.add(monitorBarang, "card2");

        judulTambah.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        judulTambah.setText("Tambah Barang :");

        javax.swing.GroupLayout headerTambahLayout = new javax.swing.GroupLayout(headerTambah);
        headerTambah.setLayout(headerTambahLayout);
        headerTambahLayout.setHorizontalGroup(
            headerTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerTambahLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(judulTambah)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerTambahLayout.setVerticalGroup(
            headerTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerTambahLayout.createSequentialGroup()
                .addGap(0, 60, Short.MAX_VALUE)
                .addComponent(judulTambah))
        );

        labelNama.setText("Nama :");

        labelHarga.setText("Harga Jual :");

        labelStok.setText("Stok :");

        teksHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teksHargaActionPerformed(evt);
            }
        });

        teksStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teksStokActionPerformed(evt);
            }
        });

        labelTanggalMasuk.setText("Tanggal Masuk :");

        btnTambah.setText("tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnKembali.setText("kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        llabelKadaluarsa.setText("Kadaluarsa :");

        jLabel1.setText("Harga Beli");

        javax.swing.GroupLayout bodyTambahGudangLayout = new javax.swing.GroupLayout(bodyTambahGudang);
        bodyTambahGudang.setLayout(bodyTambahGudangLayout);
        bodyTambahGudangLayout.setHorizontalGroup(
            bodyTambahGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyTambahGudangLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(bodyTambahGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelStok)
                    .addComponent(labelTanggalMasuk)
                    .addComponent(llabelKadaluarsa)
                    .addComponent(jLabel1)
                    .addComponent(labelNama)
                    .addComponent(labelHarga))
                .addGap(47, 47, 47)
                .addGroup(bodyTambahGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(bodyTambahGudangLayout.createSequentialGroup()
                        .addComponent(btnKembali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                        .addComponent(btnTambah))
                    .addComponent(teksNama, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teksHarga, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teksStok, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggalKadaluarsa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tanggalMasukTambah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputHargaBeli))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        bodyTambahGudangLayout.setVerticalGroup(
            bodyTambahGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyTambahGudangLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(bodyTambahGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNama)
                    .addComponent(teksNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(bodyTambahGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bodyTambahGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teksHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHarga))
                .addGap(27, 27, 27)
                .addGroup(bodyTambahGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelStok)
                    .addComponent(teksStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bodyTambahGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(llabelKadaluarsa)
                    .addComponent(tanggalKadaluarsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bodyTambahGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTanggalMasuk)
                    .addComponent(tanggalMasukTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(bodyTambahGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKembali)
                    .addComponent(btnTambah))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tambahBarangLayout = new javax.swing.GroupLayout(tambahBarang);
        tambahBarang.setLayout(tambahBarangLayout);
        tambahBarangLayout.setHorizontalGroup(
            tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bodyTambahGudang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tambahBarangLayout.setVerticalGroup(
            tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahBarangLayout.createSequentialGroup()
                .addComponent(headerTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bodyTambahGudang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 103, Short.MAX_VALUE))
        );

        mainGudang.add(tambahBarang, "card3");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Ubah Data Barang :");

        javax.swing.GroupLayout headerUbahLayout = new javax.swing.GroupLayout(headerUbah);
        headerUbah.setLayout(headerUbahLayout);
        headerUbahLayout.setHorizontalGroup(
            headerUbahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerUbahLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addContainerGap(553, Short.MAX_VALUE))
        );
        headerUbahLayout.setVerticalGroup(
            headerUbahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerUbahLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        labelUbahNama.setText("Nama :");

        labelUbahHarga.setText("Harga :");

        labelUbahStok.setText("Stok :");

        labelUbahKadaluarsa.setText("Kadaluarsa :");

        teksUbahNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teksUbahNamaActionPerformed(evt);
            }
        });

        btnSimpan.setText("simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatalUbah.setText("batal");
        btnBatalUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalUbahActionPerformed(evt);
            }
        });

        outputStok.setText("Jumlah stok pcs");

        labelHargaBeli.setText("Harga Beli :");

        javax.swing.GroupLayout bodyUbahLayout = new javax.swing.GroupLayout(bodyUbah);
        bodyUbah.setLayout(bodyUbahLayout);
        bodyUbahLayout.setHorizontalGroup(
            bodyUbahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyUbahLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(bodyUbahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUbahNama)
                    .addComponent(labelUbahHarga)
                    .addComponent(labelUbahStok)
                    .addComponent(labelUbahKadaluarsa)
                    .addComponent(labelHargaBeli))
                .addGap(45, 45, 45)
                .addGroup(bodyUbahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyUbahLayout.createSequentialGroup()
                        .addComponent(btnBatalUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSimpan))
                    .addComponent(teksUbahHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addComponent(teksUbahNama)
                    .addComponent(tanggalUbahKadaluarsa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outputStok)
                    .addComponent(teksHargaBeli))
                .addContainerGap(285, Short.MAX_VALUE))
        );
        bodyUbahLayout.setVerticalGroup(
            bodyUbahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyUbahLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(bodyUbahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUbahNama)
                    .addComponent(teksUbahNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bodyUbahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUbahHarga)
                    .addComponent(teksUbahHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(bodyUbahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHargaBeli)
                    .addComponent(teksHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(bodyUbahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUbahStok)
                    .addComponent(outputStok))
                .addGap(18, 18, 18)
                .addGroup(bodyUbahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggalUbahKadaluarsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUbahKadaluarsa))
                .addGap(18, 18, 18)
                .addGroup(bodyUbahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatalUbah)
                    .addComponent(btnSimpan))
                .addContainerGap(297, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout updateBarangLayout = new javax.swing.GroupLayout(updateBarang);
        updateBarang.setLayout(updateBarangLayout);
        updateBarangLayout.setHorizontalGroup(
            updateBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bodyUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        updateBarangLayout.setVerticalGroup(
            updateBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateBarangLayout.createSequentialGroup()
                .addComponent(headerUbah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bodyUbah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainGudang.add(updateBarang, "card4");

        judulStok.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        judulStok.setText("Tambah Stok Barang :");

        javax.swing.GroupLayout headerStokLayout = new javax.swing.GroupLayout(headerStok);
        headerStok.setLayout(headerStokLayout);
        headerStokLayout.setHorizontalGroup(
            headerStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerStokLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(judulStok)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerStokLayout.setVerticalGroup(
            headerStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerStokLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(judulStok)
                .addContainerGap())
        );

        labelNamaStok.setText("Nama");

        labelHargaStok.setText("Harga");

        labelStokSekarang.setText("Stok Sekarang");

        labelMasuk.setText("Tanggal Masuk");

        labelTanggalKadaluarsa.setText("Tanggal Kadaluarsa");

        labelTambahStok.setText("Tambahan Stok");

        teksTambahanStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teksTambahanStokActionPerformed(evt);
            }
        });

        namaBarang.setText("Nama Barang");

        HargaBarang.setText("Harga Barang");

        stokSekarang.setText("Stok Sekarang pcs");

        btnTambahStok.setText("tambah");
        btnTambahStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahStokActionPerformed(evt);
            }
        });

        btnSelesai.setText("selesai");
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });

        jLabel3.setText("pcs");

        labelBeli.setText("Harga Beli");

        outputHargaBeli.setText("Harga Beli");

        javax.swing.GroupLayout bodyStokLayout = new javax.swing.GroupLayout(bodyStok);
        bodyStok.setLayout(bodyStokLayout);
        bodyStokLayout.setHorizontalGroup(
            bodyStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyStokLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(bodyStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyStokLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(btnSelesai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTambahStok)
                        .addGap(261, 261, 261))
                    .addGroup(bodyStokLayout.createSequentialGroup()
                        .addGroup(bodyStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTambahStok)
                            .addComponent(labelMasuk)
                            .addComponent(labelNamaStok)
                            .addComponent(labelHargaStok)
                            .addComponent(labelStokSekarang)
                            .addComponent(labelTanggalKadaluarsa)
                            .addComponent(labelBeli))
                        .addGap(50, 50, 50)
                        .addGroup(bodyStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bodyStokLayout.createSequentialGroup()
                                .addComponent(outputHargaBeli)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(bodyStokLayout.createSequentialGroup()
                                .addGroup(bodyStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tanggalMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(teksTambahanStok)
                                    .addComponent(tanggalExpStok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                                    .addGroup(bodyStokLayout.createSequentialGroup()
                                        .addGroup(bodyStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(HargaBarang)
                                            .addComponent(namaBarang)
                                            .addGroup(bodyStokLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(stokSekarang)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel3)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(264, 264, 264))))))
        );
        bodyStokLayout.setVerticalGroup(
            bodyStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyStokLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(bodyStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNamaStok)
                    .addComponent(namaBarang))
                .addGap(18, 18, 18)
                .addGroup(bodyStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHargaStok)
                    .addComponent(HargaBarang))
                .addGap(27, 27, 27)
                .addGroup(bodyStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBeli)
                    .addComponent(outputHargaBeli))
                .addGap(42, 42, 42)
                .addGroup(bodyStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStokSekarang)
                    .addComponent(stokSekarang, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(25, 25, 25)
                .addGroup(bodyStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bodyStokLayout.createSequentialGroup()
                        .addComponent(labelTambahStok)
                        .addGap(24, 24, 24)
                        .addComponent(labelMasuk)
                        .addGap(22, 22, 22))
                    .addGroup(bodyStokLayout.createSequentialGroup()
                        .addComponent(teksTambahanStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tanggalMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(bodyStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTanggalKadaluarsa)
                    .addComponent(tanggalExpStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bodyStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelesai)
                    .addComponent(btnTambahStok))
                .addContainerGap(242, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tambahStokLayout = new javax.swing.GroupLayout(tambahStok);
        tambahStok.setLayout(tambahStokLayout);
        tambahStokLayout.setHorizontalGroup(
            tambahStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerStok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bodyStok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tambahStokLayout.setVerticalGroup(
            tambahStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahStokLayout.createSequentialGroup()
                .addComponent(headerStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bodyStok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainGudang.add(tambahStok, "card5");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Daftar Suply :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(23, 23, 23))
        );

        tabelSuply.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelSuply);

        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariKeyReleased(evt);
            }
        });

        jLabel5.setText("Cari : ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)
                        .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout suplyLayout = new javax.swing.GroupLayout(suply);
        suply.setLayout(suplyLayout);
        suplyLayout.setHorizontalGroup(
            suplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        suplyLayout.setVerticalGroup(
            suplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suplyLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainGudang.add(suply, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainGudang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainGudang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void monitorManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monitorManagerActionPerformed
        // TODO add your handling code here:
        mainGudang.removeAll();
        mainGudang.repaint();
        mainGudang.revalidate();
        
        mainGudang.add(monitorBarang);
        mainGudang.repaint();
        mainGudang.revalidate();
        try {
            tampilkanProduk();
        } catch (SQLException ex) {
            Logger.getLogger(GudangProsesView.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_monitorManagerActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new mainView().setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        mainGudang.removeAll();
        mainGudang.repaint();
        mainGudang.revalidate();
        
        mainGudang.add(tambahBarang);
        mainGudang.repaint();
        mainGudang.revalidate();
        
        teksNama.setText("");
        inputHargaBeli.setText("");
        teksHarga.setText("");
        teksStok.setText("");
        tanggalKadaluarsa.setDate(null);
        tanggalMasukTambah.setDate(null);
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void inputCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCariActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int i;
        Date date = null;
        
        if(tabelGudang.getSelectedRow() > -1){
            // ubah tampilan ke update
            mainGudang.removeAll();
            mainGudang.repaint();
            mainGudang.revalidate();

            mainGudang.add(updateBarang);
            mainGudang.repaint();
            mainGudang.revalidate();
            
            
            //isi form update
            i = tabelGudang.getSelectedRow();
            
            try {
                date = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(i,5));
            } catch (ParseException ex) {
                Logger.getLogger(ManagerProsesView.class.getName()).log(Level.SEVERE, null, ex);
            }
            teksUbahNama.setText((String) model.getValueAt(i, 1));
            teksUbahHarga.setText((String) model.getValueAt(i, 3));
            teksHargaBeli.setText((String) model.getValueAt(i, 2));
            outputStok.setText((String) model.getValueAt(i,4) + " pcs");
            tanggalUbahKadaluarsa.setDate(date);
            
        }else{
            JOptionPane.showMessageDialog(null, "pilih data produk");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void teksStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teksStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teksStokActionPerformed

    private void teksHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teksHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teksHargaActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        
        //cek form data
        if(teksNama.getText().equals("")){
            
            JOptionPane.showMessageDialog(null, "isi nama barang");
            
        }else if(inputHargaBeli.getText().equals("")){
            
            JOptionPane.showMessageDialog(null, "isi harga beli");
            
        }else if(teksHarga.getText().equals("")){
            
             JOptionPane.showMessageDialog(null, "isi harga jual");
            
        }else if(teksStok.getText().equals("")){
            
            JOptionPane.showMessageDialog(null, "isi stok");
            
        }else if(tanggalMasukTambah.getDate() == null || tanggalKadaluarsa.getDate() == null){
            
            JOptionPane.showMessageDialog(null, "isi tanggal masuk/kadaluarsa");
            
        }else{
            
            try {
                //insert ke tabel produk
                String namaBarang = teksNama.getText();
                int harga = Integer.parseInt(teksHarga.getText());
                int hargaBeli = Integer.parseInt(inputHargaBeli.getText());
                int stok = Integer.parseInt(teksStok.getText());      
                Date tanggal = tanggalMasukTambah.getDate();  
                Date tanggal2 = tanggalKadaluarsa.getDate();
                java.sql.Date tanggalMasuk = new java.sql.Date(tanggal.getTime());
                java.sql.Date kadaluarsa = new java.sql.Date(tanggal2.getTime());


                PreparedStatement ps;
                ResultSet rs;
                String query1 = "INSERT INTO `produk`(`nama_produk`, `harga_beli`, `harga_produk`, `stok_produk`, `kadaluarsa`) VALUES (?,?,?,?,?)";
                String query2 = "INSERT INTO `suply`(`id_petugas`, `id_produk`, `harga_beli`, `harga_jual`, `stok_masuk`, `tanggal_masuk`) VALUES (?,?,?,?,?,?)";
                

                ps = MyConnection.getConnection().prepareStatement(query1);

                ps.setString(1, namaBarang);
                ps.setInt(2, hargaBeli);
                ps.setInt(3, harga);
                ps.setInt(4, stok);
                ps.setDate(5, kadaluarsa);
                ps.executeUpdate();

                //ambil id Produk
                Statement stm = MyConnection.getConnection().createStatement();
                rs = stm.executeQuery("SELECT id_produk FROM produk WHERE nama_produk = '" + namaBarang +"'");
                rs.next();
                int id_produk = rs.getInt("id_produk");

                //insert ke tabel suply
                ps = MyConnection.getConnection().prepareStatement(query2);
                ps.setInt(1, this.id_user);
                ps.setInt(2, id_produk);
                ps.setInt(3, hargaBeli);
                ps.setInt(4, harga);
                ps.setInt(5, stok);
                ps.setDate(6, tanggalMasuk);
                ps.executeUpdate();

                JOptionPane.showMessageDialog(null, "data berhasil ditambah");

                //kembali ke monitor
                mainGudang.removeAll();
                mainGudang.repaint();
                mainGudang.revalidate();

                mainGudang.add(monitorBarang);
                mainGudang.repaint();
                mainGudang.revalidate();
                tampilkanProduk();
            } catch (SQLException ex) {
                Logger.getLogger(GudangProsesView.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "isi data dengan lengakap");      
            }
            
        }
        
        
        
        
            
        
        
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        mainGudang.removeAll();
        mainGudang.repaint();
        mainGudang.revalidate();
        
        mainGudang.add(monitorBarang);
        mainGudang.repaint();
        mainGudang.revalidate();
        try {
            tampilkanProduk();
        } catch (SQLException ex) {
            Logger.getLogger(GudangProsesView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void teksUbahNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teksUbahNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teksUbahNamaActionPerformed

    private void btnBatalUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalUbahActionPerformed
        // TODO add your handling code here:
        mainGudang.removeAll();
        mainGudang.repaint();
        mainGudang.revalidate();
        
        mainGudang.add(monitorBarang);
        mainGudang.repaint();
        mainGudang.revalidate();
        try{
            tampilkanProduk();
        } catch (SQLException ex){
            Logger.getLogger(GudangProsesView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBatalUbahActionPerformed

    private void btnStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStokActionPerformed
        // TODO add your handling code here:
        int i;
        Date date = null;
        
        if(tabelGudang.getSelectedRow() > -1){
            // ubah tampilan ke update
            mainGudang.removeAll();
            mainGudang.repaint();
            mainGudang.revalidate();

            mainGudang.add(tambahStok);
            mainGudang.repaint();
            mainGudang.revalidate();
            
            
            //isi form update
            i = tabelGudang.getSelectedRow();
            
            try {
                date = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(i,5));
            } catch (ParseException ex) {
                Logger.getLogger(ManagerProsesView.class.getName()).log(Level.SEVERE, null, ex);
            }
            namaBarang.setText((String) model.getValueAt(i, 1));
            HargaBarang.setText((String) model.getValueAt(i, 3));
            outputHargaBeli.setText((String) model.getValueAt(i, 2));
            stokSekarang.setText((String) model.getValueAt(i,4));
        }else{
            JOptionPane.showMessageDialog(null, "pilih data produk");
        }
    }//GEN-LAST:event_btnStokActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int i;
        if(tabelGudang.getSelectedRow()>-1){
            i = tabelGudang.getSelectedRow();
            int id_produk = Integer.parseInt((String) model.getValueAt(i, 0));
            
            PreparedStatement ps;
            String query = "DELETE FROM `produk` WHERE `produk`.`id_produk` = ?";
            
            try {
                ps = MyConnection.getConnection().prepareStatement(query);
                ps.setInt(1, id_produk);
                ps.executeUpdate();
                tampilkanProduk();
            } catch (SQLException ex) {
                Logger.getLogger(ManagerProsesView.class.getName()).log(Level.SEVERE, null, ex);
            }        
            
        }else{
            JOptionPane.showMessageDialog(null, "pilih data");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void cekBoxHabisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cekBoxHabisMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cekBoxHabisMouseClicked

    private void cekBoxHabisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekBoxHabisActionPerformed
        // TODO add your handling code here:
        if(cekBoxHabis.isSelected()){
            
            stokHabis.setEditable(true);
            btnCek2.setEnabled(true);
            tanggalExp.setDate(null);
            
        } else{
            stokHabis.setEditable(false);
            btnCek2.setEnabled(false);
            try {
                tampilkanProduk();
            } catch (SQLException ex) {
                Logger.getLogger(GudangProsesView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cekBoxHabisActionPerformed

    private void teksTambahanStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teksTambahanStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teksTambahanStokActionPerformed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        // TODO add your handling code here:
        mainGudang.removeAll();
        mainGudang.repaint();
        mainGudang.revalidate();
        
        mainGudang.add(monitorBarang);
        mainGudang.repaint();
        mainGudang.revalidate();
        try{
            tampilkanProduk();
        } catch (SQLException ex){
            Logger.getLogger(GudangProsesView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSelesaiActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        try {
            // TODO add your handling code here:
            tampilkanProduk();
            inputCari.setText("");
            tanggalExp.setDate(null);
            cekBoxHabis.setSelected(false);
            stokHabis.setEditable(false);
            btnCek2.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(GudangProsesView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        
        if(teksUbahNama.getText().equals("")){
            
            JOptionPane.showMessageDialog(null, "isi nama barang");
            
        }else if(teksHargaBeli.getText().equals("")){
            
            JOptionPane.showMessageDialog(null, "isi harga beli");
            
        }else if(teksUbahHarga.getText().equals("")){
            
             JOptionPane.showMessageDialog(null, "isi harga jual");
            
        }else if(tanggalUbahKadaluarsa.getDate() == null){
            
            JOptionPane.showMessageDialog(null, "isi tanggal kadaluarsa");
            
        }else{
            
            int i = tabelGudang.getSelectedRow();
        
            //inisialisasi data yang akan dimasukan ke dalam database
            int id_produk = Integer.parseInt((String) model.getValueAt(i, 0));
            String namaBarang =  teksUbahNama.getText();
            int harga = Integer.parseInt(teksUbahHarga.getText());
            int hargaBeli = Integer.parseInt(teksHargaBeli.getText());
            Date date = tanggalUbahKadaluarsa.getDate();
            java.sql.Date kadaluarsa = new java.sql.Date(date.getTime());

            //proses update data pada database
            PreparedStatement ps;
            String query = "UPDATE produk SET \n" +
                            "nama_produk = ?,\n" +
                            "harga_beli = ?,\n" +
                            "harga_produk = ?,\n" +
                            "kadaluarsa = ?\n" +
                            "WHERE id_produk = ?";

            try {
                ps = MyConnection.getConnection().prepareStatement(query);
                ps.setString(1, namaBarang);
                ps.setInt(2, hargaBeli);
                ps.setInt(3, harga);
                ps.setDate(4, kadaluarsa);
                ps.setInt(5, id_produk);
                ps.executeUpdate();

                JOptionPane.showMessageDialog(null, "data berhasil di update");

                //balik ke monitor
                mainGudang.removeAll();
                mainGudang.repaint();
                mainGudang.revalidate();

                mainGudang.add(monitorBarang);
                mainGudang.repaint();
                mainGudang.revalidate();
                tampilkanProduk();

            } catch (SQLException ex) {
                Logger.getLogger(GudangProsesView.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTambahStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahStokActionPerformed
        
        
        if(teksTambahanStok.getText().equals("")){
            
            JOptionPane.showMessageDialog(null, "isi tambahan stok");
            
        }else if(tanggalMasuk.getDate() == null || tanggalExpStok.getDate() == null){
            
            JOptionPane.showMessageDialog(null, "isi tanggal masuk/kadaluarsa");
            
        }else{
            
            int i = tabelGudang.getSelectedRow();
        
            //inisialisasi data yang akan dimasukan ke dalam database
            int id_produk = Integer.parseInt((String) model.getValueAt(i, 0));
            int stokLama = Integer.parseInt(stokSekarang.getText());
            int tambahanStok = Integer.parseInt(teksTambahanStok.getText());
            int stokBaru = stokLama + tambahanStok;
            int hargaJual = Integer.parseInt(HargaBarang.getText());
            int hargaBeli = Integer.parseInt(outputHargaBeli.getText());

            Date tanggal = tanggalMasuk.getDate();
            java.sql.Date tanggalMasuk = new java.sql.Date(tanggal.getTime());

            tanggal = tanggalExpStok.getDate();
            java.sql.Date kadaluarsa = new java.sql.Date(tanggal.getTime());


            PreparedStatement ps;
            ResultSet rs;
            String query1 = "UPDATE produk SET "
                             + "stok_produk = ?,"
                             + "kadaluarsa = ?"
                             + "WHERE id_produk = ?";
            String query2 = "INSERT INTO `suply`(`id_petugas`, `id_produk`, `stok_masuk`, `harga_jual`, `harga_beli`, `tanggal_masuk`) VALUES (?,?,?,?,?,?)";


            try {
                //update ke tabel produk
                ps = MyConnection.getConnection().prepareStatement(query1);

                ps.setInt(1, stokBaru);
                ps.setDate(2, kadaluarsa);
                ps.setInt(3, id_produk);
                ps.executeUpdate();           

                //insert ke tabel suply
                ps = MyConnection.getConnection().prepareStatement(query2);
                ps.setInt(1, this.id_user);
                ps.setInt(2, id_produk);
                ps.setInt(3, tambahanStok);
                ps.setInt(4, hargaJual);
                ps.setInt(5, hargaBeli);
                ps.setDate(6, tanggalMasuk);
                ps.executeUpdate();

                JOptionPane.showMessageDialog(null, "stok berhasil ditambah");

                //balik ke monitor
                mainGudang.removeAll();
                mainGudang.repaint();
                mainGudang.revalidate();

                mainGudang.add(monitorBarang);
                mainGudang.repaint();
                mainGudang.revalidate();
                tampilkanProduk();
            } catch (SQLException ex) {
                Logger.getLogger(GudangProsesView.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        
        
        
    }//GEN-LAST:event_btnTambahStokActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        
        String str = inputCari.getText();
        cariData(str);
        
    }//GEN-LAST:event_btnCariActionPerformed

    private void tanggalExpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tanggalExpMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalExpMouseClicked

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
        // TODO add your handling code here:
        cekBoxHabis.setSelected(false);
        stokHabis.setEditable(false);
        btnCek2.setEnabled(false);
        
        if(tanggalExp.getDate()== null){
            JOptionPane.showMessageDialog(null, "masukan tanggal");
        } else{
            Date date = tanggalExp.getDate();
            java.sql.Date kadaluarsa = new java.sql.Date(date.getTime());

            String query = "SELECT * FROM `produk` WHERE kadaluarsa < '"+kadaluarsa+"'";

            ResultSet rs;
            try {
                Statement stm = MyConnection.getConnection().createStatement();
                rs = stm.executeQuery(query);

                clearTable(tabelGudang, model);
                while(rs.next()){
                    String data[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6)};
                    model.addRow(data);
                }

            } catch (SQLException ex) {
                Logger.getLogger(GudangProsesView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    }//GEN-LAST:event_btnCekActionPerformed

    private void stokHabisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stokHabisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stokHabisActionPerformed

    private void btnCek2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCek2ActionPerformed
        // TODO add your handling code here:
            int Habis = Integer.parseInt(stokHabis.getText());
            String query = "SELECT * FROM produk WHERE stok_produk <= " + Habis;
            ResultSet rs;
            
            try {
                Statement stm = MyConnection.getConnection().createStatement();
                rs = stm.executeQuery(query);
                
                clearTable(tabelGudang, model);
                while(rs.next()){
                    
                    String data[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6)};
                    model.addRow(data);
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(GudangProsesView.class.getName()).log(Level.SEVERE, null, ex);
            }
    
    }//GEN-LAST:event_btnCek2ActionPerformed

    private void btnSuplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuplyActionPerformed
        // TODO add your handling code here:
        mainGudang.removeAll();
        mainGudang.repaint();
        mainGudang.revalidate();
        
        mainGudang.add(suply);
        mainGudang.repaint();
        mainGudang.revalidate();
        try {
            tampilkanSuply();
        } catch (SQLException ex) {
            Logger.getLogger(GudangProsesView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSuplyActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariActionPerformed

    private void cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyReleased
       
        try {
            tampilkanSuply();
        } catch (SQLException ex) {
            Logger.getLogger(GudangProsesView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GudangProsesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GudangProsesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GudangProsesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GudangProsesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            private boolean login = this.login;
            public void run() {
//                String username = "yoga";
//                try {
//                    GudangProsesView gp;
//                     gp = new GudangProsesView (username);
//                     gp.setVisible(true);
//                     gp.labelJudulGudang.setText("Wecome " + username + ", Semangat!!!");
//                } catch (SQLException ex) {
//                    Logger.getLogger(GudangProsesView.class.getName()).log(Level.SEVERE, null, ex);
//                }
                 if (!login){
                    new mainView().setVisible(true);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HargaBarang;
    private javax.swing.JPanel bodyGudang;
    private javax.swing.JPanel bodyStok;
    private javax.swing.JPanel bodyTambahGudang;
    private javax.swing.JPanel bodyUbah;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBatalUbah;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCek;
    private javax.swing.JButton btnCek2;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnStok;
    private javax.swing.JButton btnSuply;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTambahStok;
    private javax.swing.JTextField cari;
    private javax.swing.JCheckBox cekBoxHabis;
    private javax.swing.JLabel cekExp;
    private javax.swing.JPanel headerStok;
    private javax.swing.JPanel headerTambah;
    private javax.swing.JPanel headerUbah;
    private javax.swing.JTextField inputCari;
    private javax.swing.JTextField inputHargaBeli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel judulGudang;
    private javax.swing.JLabel judulStok;
    private javax.swing.JLabel judulTambah;
    private javax.swing.JLabel labelBeli;
    private javax.swing.JLabel labelCariBarang;
    private javax.swing.JLabel labelHarga;
    private javax.swing.JLabel labelHargaBeli;
    private javax.swing.JLabel labelHargaStok;
    public javax.swing.JLabel labelJudulGudang;
    private javax.swing.JLabel labelMasuk;
    private javax.swing.JLabel labelMenu;
    private javax.swing.JLabel labelMerk;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNamaStok;
    private javax.swing.JLabel labelStok;
    private javax.swing.JLabel labelStokSekarang;
    private javax.swing.JLabel labelTambahStok;
    private javax.swing.JLabel labelTanggalKadaluarsa;
    private javax.swing.JLabel labelTanggalMasuk;
    private javax.swing.JLabel labelUbahHarga;
    private javax.swing.JLabel labelUbahKadaluarsa;
    private javax.swing.JLabel labelUbahNama;
    private javax.swing.JLabel labelUbahStok;
    private javax.swing.JLabel llabelKadaluarsa;
    private javax.swing.JPanel mainGudang;
    private javax.swing.JPanel menuManager;
    private javax.swing.JPanel monitorBarang;
    private javax.swing.JButton monitorManager;
    private javax.swing.JLabel namaBarang;
    private javax.swing.JLabel outputHargaBeli;
    private javax.swing.JLabel outputStok;
    private javax.swing.JScrollPane panelTabelGudang;
    private javax.swing.JTextField stokHabis;
    private javax.swing.JLabel stokSekarang;
    private javax.swing.JPanel suply;
    private javax.swing.JTable tabelGudang;
    private javax.swing.JTable tabelSuply;
    private javax.swing.JPanel tambahBarang;
    private javax.swing.JPanel tambahStok;
    private com.toedter.calendar.JDateChooser tanggalExp;
    private com.toedter.calendar.JDateChooser tanggalExpStok;
    private com.toedter.calendar.JDateChooser tanggalKadaluarsa;
    private com.toedter.calendar.JDateChooser tanggalMasuk;
    private com.toedter.calendar.JDateChooser tanggalMasukTambah;
    private com.toedter.calendar.JDateChooser tanggalUbahKadaluarsa;
    private javax.swing.JTextField teksHarga;
    private javax.swing.JTextField teksHargaBeli;
    private javax.swing.JTextField teksNama;
    private javax.swing.JTextField teksStok;
    private javax.swing.JTextField teksTambahanStok;
    private javax.swing.JTextField teksUbahHarga;
    private javax.swing.JTextField teksUbahNama;
    private javax.swing.JPanel updateBarang;
    // End of variables declaration//GEN-END:variables

    
    private void tampilkanProduk () throws SQLException{
        clearTable(tabelGudang, model);
        
        Statement stm = MyConnection.getConnection().createStatement();
        ResultSet rs;
        rs = stm.executeQuery("SELECT * FROM produk");

        while(rs.next()){
            String data[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6)};
            model.addRow(data);
        }
        
        
    }
    
    private void tampilkanSuply() throws SQLException{
        clearTable(tabelSuply, model2);
        String str = cari.getText();
        
        Statement stm = MyConnection.getConnection().createStatement();
        ResultSet rs;
        rs = stm.executeQuery("SELECT s.id_suply, u.username, p.nama_produk, s.stok_masuk, s.harga_jual, s.harga_beli,s.tanggal_masuk\n"
                + "FROM suply s INNER JOIN user u INNER JOIN produk p\n"
                + "ON s.id_produk = p.id_produk AND s.id_petugas = u.id_user\n"
                + "WHERE s.id_petugas = " + this.id_user + " AND (\n"
                +"s.id_suply LIKE '%"+str+"%' OR\n" +
                "u.username LIKE '%"+str+"%'OR\n" +
                "p.nama_produk LIKE '%"+str+"%'OR\n" +
                "s.stok_masuk LIKE '%"+str+"%'OR\n" +
                "s.harga_jual LIKE '%"+str+"%'OR\n" +
                "s.harga_beli LIKE '%"+str+"%'OR\n" +
                "s.tanggal_masuk LIKE '%"+str+"%')"  
        );

        while(rs.next()){
            String data[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)};
            model2.addRow(data);
        }
    }
    
    private void isiAtributTabel() {
         String[] judul = {
             "id_produk",
            "Nama",
            "Harga Beli",
             "Harga Jual",
             "Stok (pcs)",
             "kadaluarsa"
         };
          model = new DefaultTableModel(judul,0);
          tabelGudang.setModel(model);
    }
    
//    public void clearTable(){
//        int row = tabelGudang.getRowCount();
//
//        for(int a=0; a<row; a++){
//            model.removeRow(0);
//        }
//    }
    
    public void clearTable(javax.swing.JTable tabel, DefaultTableModel model){
        int row = tabel.getRowCount();

        for(int a=0; a<row; a++){
            model.removeRow(0);
        }
    }
    
    private void cariData(String str) {
        clearTable(tabelGudang, model);
        ResultSet rs;
        Statement stm;
        String query = "SELECT * FROM produk\n" +
                        "WHERE \n" +
                        "id_produk LIKE '%"+str+"%' OR\n" +
                        "nama_produk LIKE '%"+str+"%'OR\n" +
                        "harga_produk LIKE '%"+str+"%'OR\n" +
                        "stok_produk LIKE '%"+str+"%'OR\n" +
                        "kadaluarsa LIKE '%"+str+"%'";                      
            
        try {
            
           stm = MyConnection.getConnection().createStatement();
           rs = stm.executeQuery(query);
            
            while(rs.next()){
            String data[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6)};
            model.addRow(data);
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(ManagerProsesView.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }
    
    
    
    private void isiAtributTabelSuply(){
        String[] judul = {
             "id_suply",
            "nama petugas",
             "nama produk",
             "Stok Masuk",
             "Harga Jual",
             "Harga Beli",
             "Tanggal Masuk"
         };
          model2 = new DefaultTableModel(judul,0);
          tabelSuply.setModel(model2);
    }
    
    private int getId(String username) throws SQLException{
        
        Statement stm = MyConnection.getConnection().createStatement();
        ResultSet rs;
        rs = stm.executeQuery("SELECT id_user FROM user WHERE username = '" + username + "'");
        rs.next();
        int id = rs.getInt("id_user");
        
        return id;
        
    }
}
