/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir_kelompok2;

import java.awt.Color;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alitz
 */
public class mainView extends javax.swing.JFrame {

    /**
     * Creates new form mainView
     */
    public mainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        bodyPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        keluarBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        loginMenu = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        judulLogin = new javax.swing.JLabel();
        inputUsername = new javax.swing.JTextField();
        inputPass = new javax.swing.JPasswordField();
        btnSubmit = new javax.swing.JButton();
        cumaLabel = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        labelUsername = new javax.swing.JLabel();
        labelPass = new javax.swing.JLabel();
        register = new javax.swing.JPanel();
        judulRegister = new javax.swing.JLabel();
        registerUsername = new javax.swing.JLabel();
        registerEmail = new javax.swing.JLabel();
        registerRole = new javax.swing.JLabel();
        registerPass = new javax.swing.JLabel();
        registerRePass = new javax.swing.JLabel();
        registerNoHp = new javax.swing.JLabel();
        regInputUsername = new javax.swing.JTextField();
        regInputEmail = new javax.swing.JTextField();
        regInputNoHp = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        regInputPass = new javax.swing.JPasswordField();
        regInputRePass = new javax.swing.JPasswordField();
        comboBoxRole = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPanel.setBackground(new java.awt.Color(0, 0, 102));

        judul.setBackground(new java.awt.Color(255, 255, 255));
        judul.setFont(new java.awt.Font("Adobe Caslon Pro", 3, 18)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 255, 255));
        judul.setText("<html> \n<p><center>Kasir<br>Sejahtera..</center></p>\n</html>");

        keluarBtn.setBackground(new java.awt.Color(153, 0, 0));
        keluarBtn.setForeground(new java.awt.Color(255, 0, 51));
        keluarBtn.setToolTipText("Keluar");
        keluarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                keluarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                keluarBtnMouseExited(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Keluarr");

        javax.swing.GroupLayout keluarBtnLayout = new javax.swing.GroupLayout(keluarBtn);
        keluarBtn.setLayout(keluarBtnLayout);
        keluarBtnLayout.setHorizontalGroup(
            keluarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keluarBtnLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        keluarBtnLayout.setVerticalGroup(
            keluarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keluarBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loginMenu.setBackground(new java.awt.Color(153, 255, 255));
        loginMenu.setText("Login");
        loginMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(keluarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(loginMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(281, 281, 281)
                .addComponent(loginMenu)
                .addGap(18, 18, 18)
                .addComponent(keluarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(153, 255, 255));
        mainPanel.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        judulLogin.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        judulLogin.setText("LOGIN");

        inputUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUsernameActionPerformed(evt);
            }
        });

        inputPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPassActionPerformed(evt);
            }
        });

        btnSubmit.setText("submit");
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitMouseClicked(evt);
            }
        });
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        cumaLabel.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        cumaLabel.setText("skuy login dulu !!");

        btnRegister.setText("register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        labelUsername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelUsername.setText("Username :");

        labelPass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelPass.setText("Password :");

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUsername)
                    .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(loginLayout.createSequentialGroup()
                            .addComponent(btnRegister)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                            .addComponent(btnSubmit))
                        .addComponent(cumaLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(labelPass))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputPass, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(130, 130, 130))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addComponent(judulLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(222, 222, 222))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(judulLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(cumaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsername))
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPass))
                .addGap(35, 35, 35)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnRegister))
                .addContainerGap(293, Short.MAX_VALUE))
        );

        mainPanel.add(login, "card5");

        judulRegister.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        judulRegister.setText("REGISTER");

        registerUsername.setText("Username   :");

        registerEmail.setText("E-mail          : ");

        registerRole.setText("Role             :");

        registerPass.setText("Password     :");

        registerRePass.setText("Re-Password :");

        registerNoHp.setText("No. HP         :");

        regInputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regInputEmailActionPerformed(evt);
            }
        });

        btnCreate.setText("create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnBack.setText("back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        regInputPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regInputPassActionPerformed(evt);
            }
        });

        comboBoxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kasir", "manager", "gudang" }));

        javax.swing.GroupLayout registerLayout = new javax.swing.GroupLayout(register);
        register.setLayout(registerLayout);
        registerLayout.setHorizontalGroup(
            registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerLayout.createSequentialGroup()
                .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registerLayout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(judulRegister))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registerLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(registerLayout.createSequentialGroup()
                                .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(registerUsername)
                                    .addComponent(registerEmail))
                                .addGap(60, 60, 60)
                                .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(regInputUsername)
                                    .addComponent(regInputEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)))
                            .addGroup(registerLayout.createSequentialGroup()
                                .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(registerNoHp)
                                    .addComponent(registerPass)
                                    .addComponent(registerRePass)
                                    .addComponent(registerRole))
                                .addGap(55, 55, 55)
                                .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboBoxRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(registerLayout.createSequentialGroup()
                                            .addComponent(btnBack)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                                            .addComponent(btnCreate))
                                        .addComponent(regInputNoHp)
                                        .addComponent(regInputPass)
                                        .addComponent(regInputRePass)))))))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        registerLayout.setVerticalGroup(
            registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(judulRegister)
                .addGap(34, 34, 34)
                .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerUsername)
                    .addComponent(regInputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerEmail)
                    .addComponent(regInputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerRole)
                    .addComponent(comboBoxRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regInputNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerNoHp))
                .addGap(24, 24, 24)
                .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerPass)
                    .addComponent(regInputPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerRePass)
                    .addComponent(regInputRePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnBack))
                .addContainerGap(236, Short.MAX_VALUE))
        );

        mainPanel.add(register, "card6");

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void keluarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarBtnMouseEntered
        // TODO add your handling code here:
        keluarBtn.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_keluarBtnMouseEntered

    private void keluarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarBtnMouseExited
        // TODO add your handling code here:
        keluarBtn.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_keluarBtnMouseExited

    private void keluarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarBtnMouseClicked
        // TODO add your handling code here:
        keluarBtn.setBackground(Color.GRAY);
        System.exit(0);
    }//GEN-LAST:event_keluarBtnMouseClicked

    private void inputUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUsernameActionPerformed

    private void inputPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPassActionPerformed

    private void btnSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSubmitMouseClicked

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps;
        ResultSet rs;
        String username = inputUsername.getText();
        String password = String.valueOf(inputPass.getPassword());
        
        //enkripsi pass
        try {
            password = hashPassword(password);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(mainView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String query = "SELECT * FROM `user` WHERE `username` =? AND `password` =?";
        
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            
            ps.setString(1, username);
            ps.setString(2, password);
            
            rs = ps.executeQuery();
            
            
            if(rs.next()){
                 //hapus
                 String role = rs.getString("role_name");
                 System.out.println(role);
                 if (role.equalsIgnoreCase("kasir")){
                    KasirProsesView kp;
                    kp = new KasirProsesView(username, true);
                    kp.setVisible(true);
                    kp.judulTransaksi.setText("Welcome " + username + ", Semangat!!");
                    
                 } else if(role.equalsIgnoreCase("manager")){
                     ManagerProsesView mp;
                     mp = new ManagerProsesView(username, true);
                     mp.setVisible(true);
                     mp.judulLabel.setText("Welcome Boss " + username + ", Semangat !!!");
                     
                 } else if (role.equalsIgnoreCase("gudang")){
                     GudangProsesView gp;
                     gp = new GudangProsesView (username, true);
                     gp.setVisible(true);
                     gp.labelJudulGudang.setText("Wecome " + username + ", Semangat!!!");
                 }
                 
              
                this.dispose();
                
            } else{
                JOptionPane.showMessageDialog(null, "password atau username salah");
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(mainView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void regInputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regInputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regInputEmailActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(register);
        mainPanel.repaint();
        mainPanel.revalidate();
        
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        String username = regInputUsername.getText();
        String email = regInputEmail.getText();
        String role_name = (String) comboBoxRole.getSelectedItem();
        String no_hp = regInputNoHp.getText();
        String password = String.valueOf(regInputPass.getPassword());
        String re_pass = String.valueOf(regInputRePass.getPassword());
        
        if(username.equals("")){
            JOptionPane.showMessageDialog(null, "tambahkan username");
        } else if(email.equals("")){
            JOptionPane.showMessageDialog(null, "tambahkan email");
        } else if(no_hp.equals("")){
            JOptionPane.showMessageDialog(null, "tambahkan nomor hp");
        } else if (password.equals("")){
            JOptionPane.showMessageDialog(null, "tambahkan password");
        } else if(!password.equals(re_pass)){
            JOptionPane.showMessageDialog(null, "ketik ulang password");
        } else{
            PreparedStatement ps;
            ResultSet rs;
            
            //enkripsi pass
            try {
                password = hashPassword(password);
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(mainView.class.getName()).log(Level.SEVERE, null, ex);
            }
                

            String query = "INSERT INTO `user`(`username`, `password`, `role_name`, `email`, `no_hp`) VALUES (?,?,?,?,?)";

            try {
                
               //cek username
               Statement stm = MyConnection.getConnection().createStatement();
               rs = stm.executeQuery("SELECT * FROM user WHERE username = '" + username + "'");
               if (rs.next()){
                   JOptionPane.showMessageDialog(null, "username sudah digunakan");
               } else {
                   
                   //kalau udah aman, baru create
                    ps = MyConnection.getConnection().prepareStatement(query);

                    ps.setString(1, username);
                    ps.setString(2, password);
                    ps.setString(3, role_name);
                    ps.setString(4, email);
                    ps.setString(5, no_hp);

                    if(ps.executeUpdate() > 0){
                        JOptionPane.showMessageDialog(null, "new user add");
                        mainPanel.removeAll();
                        mainPanel.repaint();
                        mainPanel.revalidate();

                        mainPanel.add(login);
                        mainPanel.repaint();
                        mainPanel.revalidate();
                    }
               }
                
               

            } catch (SQLException ex) {
                Logger.getLogger(mainView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
       
        
        
        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void regInputPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regInputPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regInputPassActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        //hapus
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        //isi atau panggil
        mainPanel.add(login);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnBackActionPerformed

    private void loginMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginMenuActionPerformed
        // TODO add your handling code here:
         //hapus
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        //isi atau panggil
        mainPanel.add(login);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_loginMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> comboBoxRole;
    private javax.swing.JLabel cumaLabel;
    private javax.swing.JPasswordField inputPass;
    private javax.swing.JTextField inputUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel judulLogin;
    private javax.swing.JLabel judulRegister;
    private javax.swing.JPanel keluarBtn;
    private javax.swing.JLabel labelPass;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JPanel login;
    private javax.swing.JButton loginMenu;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextField regInputEmail;
    private javax.swing.JTextField regInputNoHp;
    private javax.swing.JPasswordField regInputPass;
    private javax.swing.JPasswordField regInputRePass;
    private javax.swing.JTextField regInputUsername;
    private javax.swing.JPanel register;
    private javax.swing.JLabel registerEmail;
    private javax.swing.JLabel registerNoHp;
    private javax.swing.JLabel registerPass;
    private javax.swing.JLabel registerRePass;
    private javax.swing.JLabel registerRole;
    private javax.swing.JLabel registerUsername;
    // End of variables declaration//GEN-END:variables


private String hashPassword (String pass) throws NoSuchAlgorithmException{
    
    MessageDigest md = MessageDigest.getInstance("MD5");
    md.update(pass.getBytes());
    byte[] b = md.digest();
    StringBuffer sb = new StringBuffer();
    for (byte b1 : b){
        sb.append(Integer.toHexString(b1 & 0xff).toString());
    }
    
//    System.out.println(sb.toString());
  
    return sb.toString();
    
}

}
